name: build

on: [push]

jobs:
  build:
    name: Build & run examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@master

    - name: Build basic
      run: go build -v ./examples/basic

    - name: Run basic
      run: ./basic